//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.WorkAreas = new HashSet<WorkArea>();
            this.Labels = new HashSet<Label>();
            this.LastAreaAccesses = new HashSet<LastAreaAccess>();
        }
    
        public int areaId { get; set; }
        public string areaName { get; set; }
        public string outline { get; set; }
    
        public virtual ICollection<WorkArea> WorkAreas { get; set; }
        public virtual ICollection<Label> Labels { get; set; }
        public virtual ICollection<LastAreaAccess> LastAreaAccesses { get; set; }
    }
}
