//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public Employer()
        {
            this.WorkEmployers = new HashSet<WorkEmployer>();
        }
    
        public int employerId { get; set; }
        public string employerName { get; set; }
        public int employerStatus { get; set; }
    
        public virtual ICollection<WorkEmployer> WorkEmployers { get; set; }
    }
}
