//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastAreaAccess
    {
        public int areaId { get; set; }
        public int deviceId { get; set; }
        public int accessTime { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Device Device { get; set; }
    }
}
