//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timer
    {
        public int timerId { get; set; }
        public int createTime { get; set; }
        public int lastSignalTime { get; set; }
        public string timerUrl { get; set; }
        public int lifeTime { get; set; }
    }
}
