//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkEmployer
    {
        public WorkEmployer()
        {
            this.WorkShiftAccessEmployers = new HashSet<WorkShiftAccessEmployer>();
            this.WorkShiftNotificationEmployers = new HashSet<WorkShiftNotificationEmployer>();
        }
    
        public int workEmployerId { get; set; }
        public int workDayId { get; set; }
        public int employerId { get; set; }
        public int deviceId { get; set; }
        public int workState { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Employer Employer { get; set; }
        public virtual WorkDay WorkDay { get; set; }
        public virtual ICollection<WorkShiftAccessEmployer> WorkShiftAccessEmployers { get; set; }
        public virtual ICollection<WorkShiftNotificationEmployer> WorkShiftNotificationEmployers { get; set; }
    }
}
