//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkShift
    {
        public WorkShift()
        {
            this.WorkShiftAccessEmployers = new HashSet<WorkShiftAccessEmployer>();
            this.WorkShiftNotificationEmployers = new HashSet<WorkShiftNotificationEmployer>();
        }
    
        public int workShiftId { get; set; }
        public int workDayId { get; set; }
        public int workAreaId { get; set; }
        public int startTime { get; set; }
        public int endTime { get; set; }
        public int workShiftType { get; set; }
        public int notificationTimerDelay { get; set; }
        public int alarmTimerDelay { get; set; }
        public int shiftState { get; set; }
    
        public virtual WorkArea WorkArea { get; set; }
        public virtual ICollection<WorkShiftAccessEmployer> WorkShiftAccessEmployers { get; set; }
        public virtual ICollection<WorkShiftNotificationEmployer> WorkShiftNotificationEmployers { get; set; }
    }
}
