//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pg_web.Models
{
    using System;
    
    public enum WorkDayState : int
    {
        wdstNotStarted = 0,
        wdstInProgress = 1,
        wdstFinished = 2
    }
}
